name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - run: npm ci
      
      - run: npm run build
      
      - name: Create Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/Halko Voice-1.1.0.exe,dist/Halko Voice-portable-1.1.0.exe,dist/Halko Voice-1.1.0.exe.blockmap,dist/latest.yml"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
